name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
    paths-ignore:
      - 'README.md'  # Ignore changes to the README.md file
  pull_request:
    branches:
      - main  # Trigger on pull request only when targeting the main branch
    paths-ignore:
      - 'README.md'  # Ignore changes to the README.md file
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Build, test and analyze with SonarCloud
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=slimboi_spring-petclinic

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false  # We only want to build here, not push yet
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest

      # Scan Docker image with Trivy
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest
          severity: HIGH,CRITICAL  # Only fail on high or critical vulnerabilities

      # Push Docker image to DockerHub
      - name: Push Docker image
        if: success()  # Only push if the Trivy scan was successful
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest
          labels: latest-${{ github.ref_name }}
